version: '3.8'
services:
  web1:
    build: ./apps/web1
    container_name: web1
    ports:
      - "5000:5000"
    networks:
      - cloud-net

  web2:
    build: ./apps/web2
    container_name: web2
    ports:
      - "5001:5001"
    networks:
      - cloud-net

networks:
  cloud-net: